# Generated by Django 3.2.5 on 2021-07-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEWapp', '0002_document_contactholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
