# Generated by Django 3.2.5 on 2021-07-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEWapp', '0004_auto_20210730_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='files',
            field=models.FileField(upload_to='media'),
        ),
    ]
